### ISSUE TITLE
Error on Macro command

### ISSUE THREAD

**Issue by karsonenns** [nullEuro/python-irtoy#2]
I was able to get record/play working properly, but with Macro, I'm receiving some errors.

Tried changing like 33 to ` f.write("{name}:{ir}\n".format(name,ir))` which did seem to write properly, but when running the script, it didnt seem to fire the comments.

Error
```
Traceback (most recent call last):
  File "../irtoy.py", line 247, in <module>
    main()
  File "../irtoy.py", line 178, in main
    if not buttonMapToFile(args.file, btns):
  File "../irtoy.py", line 33, in buttonMapToFile
    f.write("{:s}:{:s}\n".format(name,ir))
TypeError: non-empty format string passed to object.__format__
```

Running this on Python 3.4.2, Linux based.

**Comment by karsonenns** [comment]
I also tried manually creating the macro file, this was the contents
```
power:NEC|223|32|16
pause:NEC|223|32|93
```

I don't know enough about IR codes / the script to know if this should be running the commands properly, any advice?

**Comment by nullEuro** [comment]
Thanks for your report! What commands (and inputs) produced the error? (both the one you used to get the buttons and to play a macro). Can you post the full output of both of these please?

**Comment by karsonenns** [comment]
Hey!

The steps I've been through to replicate this are:

1. Run `./irtoy.py buttons remote_test`
2. Press Input + Enter button on my remote.
3. When it asks if I want to enter any more buttons, enter N
4. Error pops out, file is written in a blank state.

**Comment by nullEuro** [comment]
Hi! Sorry for the late reply. Thanks for your feedback, I will look into this.
